apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv
spec:
  capacity:
    storage: 5Gi
    volumeMode: Filesystem
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retained
    storageClassName: manual
    awsElasticBlockStore:
      volumeId: vol-0d8ac0cdb765c1b6b
      fsType: ext4
      

    
  