apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv
spec:
  capacity:
    storage: 5Gi # ✅ Correct format
  volumeMode: Filesystem # ✅ Moved outside `capacity`
  accessModes: # ✅ Moved outside `capacity`
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # ✅ Moved outside `capacity`
  storageClassName: manual # ✅ Moved outside `capacity`
  awsElasticBlockStore: # ✅ Correct indentation
    volumeId: aws://us-east-1a/vol-0d8ac0cdb765c1b6b
    fsType: ext4
