apiVersion: v1
kind: Service
metadata:
  name: services
  labels:
    app: spring-app
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selectors:
    app: spring-app
  type: LoadBalaner
